version: "3.9"
services:
  backend:
    build: ./backend
    container_name: my-backend
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  frontend:
    build: ./frontend
    container_name: my-frontend
    ports:
      - "8080:80"

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
